# Place to set container - dockerize app
# 5. Pipeline produkcyjny
# • Pipeline trenowania i inferencji wdrożony na wybranej infrastrukturze:
# ◦ lokalnie / Docker / chmura (np. AWS, GCP, Azure)
# • Udostępnienie modelu:
# ◦ API (np. FastAPI / Flask)
# • Monitoring:
# ◦ logowanie predykcji
# ◦ wykrywanie driftu danych
# • Optymalizacja:
# ◦ wybór architektury (np. batch vs real-time)
# ◦ optymalizacja czasu i zasobów
